version: "3"

services:
  app: 
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgres://postgres:driven@localhost:5432/ngcash
    depends_on:
      - database
  database: 
    image: postgres:13
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=driven
      - POSTGRES_DB=postgres

networks:
